# Generated by Django 4.2.13 on 2024-06-05 16:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=uuid.uuid4, max_length=36)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('accommodation', models.IntegerField(choices=[(0, 'Tent'), (1, 'Van'), (2, 'Caravan'), (3, 'Yurt')], default=0)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('children', models.PositiveIntegerField(default=0)),
                ('booked', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['arrival'],
            },
        ),
    ]
