# Generated by Django 4.2.13 on 2024-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_accomodation_alter_booking_adults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='accomodation',
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation',
            field=models.IntegerField(choices=[(0, 'Tent'), (1, 'Van'), (2, 'Caravan'), (3, 'Yurt')], default=0),
        ),
    ]
