# Generated by Django 4.2.13 on 2024-05-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_booking_accomodation_booking_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
