# Generated by Django 4.2.13 on 2024-05-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='submitted',
            new_name='booked',
        ),
    ]
