# Generated by Django 4.2.13 on 2024-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_submitted_booking_booked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['arrival']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure',
            field=models.DateField(),
        ),
    ]
