# Generated by Django 4.2.13 on 2024-06-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_booking_booked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
